/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeuloto;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author bast
 */
public class AjoutJoueurDlg extends javax.swing.JDialog {
    private Joueur nj;//ajout d'un atribut nj de type Joueur
    private boolean ok;//ajout d'un attribut ok de type boolean
    /**
     * Creates new form AjoutJoueurDlg
     */
    public AjoutJoueurDlg(java.awt.Frame parent, boolean modal) {//affectation d'un constructeur de AjoutJoueurDlg
        super(parent, modal);
        initComponents();//ajout des différents éléments
        this.nj = new Joueur();//instanciation d'un nouveau joueur pour nj
        this.nj.setCouleur(Color.red);//affectation d'une couleur par défaut à nj
        this.ok = false;//boolean ok passer à false
        ImageIcon ic = new ImageIcon(getClass().getResource("/jeuloto/Icon/joueurDefaut.png"));//Instanciation d'un élément de type ImageIcon avec un chemin pour une image par défaut
        ImageIcon ic2 = new ImageIcon(ic.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));//Instanciation d'une image à partir de ic mais avec des réglages de tailles
        Photo.setIcon(ic2);//ajout de ic2 à photo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Centre = new javax.swing.JPanel();
        Gauche = new javax.swing.JPanel();
        PiedGauche = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        CentreGauche = new javax.swing.JPanel();
        T1 = new javax.swing.JLabel();
        T2 = new javax.swing.JLabel();
        T3 = new javax.swing.JLabel();
        T4 = new javax.swing.JLabel();
        Droite = new javax.swing.JPanel();
        PValider = new javax.swing.JPanel();
        Valider = new javax.swing.JButton();
        CentreDroit = new javax.swing.JPanel();
        Pseudo = new javax.swing.JTextField();
        Solde = new javax.swing.JTextField();
        PCouleur = new javax.swing.JPanel();
        BCouleur = new javax.swing.JButton();
        PanCouleur = new javax.swing.JPanel();
        PPhoto = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Photo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titre.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajout d'un nouveau joueur");
        Titre.add(jLabel1);

        getContentPane().add(Titre, java.awt.BorderLayout.PAGE_START);

        Centre.setLayout(new java.awt.GridLayout(1, 2));

        Gauche.setLayout(new java.awt.BorderLayout());

        PiedGauche.setLayout(new java.awt.GridLayout(1, 1));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        PiedGauche.add(Annuler);

        Gauche.add(PiedGauche, java.awt.BorderLayout.PAGE_END);

        CentreGauche.setLayout(new java.awt.GridLayout(4, 1));

        T1.setText("Pseudo?");
        CentreGauche.add(T1);

        T2.setText("Solde?");
        CentreGauche.add(T2);

        T3.setText("Couleur préférée?");
        CentreGauche.add(T3);

        T4.setText("Photo?");
        CentreGauche.add(T4);

        Gauche.add(CentreGauche, java.awt.BorderLayout.CENTER);

        Centre.add(Gauche);

        Droite.setLayout(new java.awt.BorderLayout());

        PValider.setLayout(new java.awt.GridLayout(1, 1));

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        PValider.add(Valider);

        Droite.add(PValider, java.awt.BorderLayout.PAGE_END);

        CentreDroit.setLayout(new java.awt.GridLayout(4, 1));
        CentreDroit.add(Pseudo);

        Solde.setEditable(false);
        Solde.setText("20");
        CentreDroit.add(Solde);

        PCouleur.setLayout(new java.awt.GridLayout(1, 2));

        BCouleur.setText("Choisir !");
        BCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCouleurActionPerformed(evt);
            }
        });
        PCouleur.add(BCouleur);

        javax.swing.GroupLayout PanCouleurLayout = new javax.swing.GroupLayout(PanCouleur);
        PanCouleur.setLayout(PanCouleurLayout);
        PanCouleurLayout.setHorizontalGroup(
            PanCouleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        PanCouleurLayout.setVerticalGroup(
            PanCouleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        PCouleur.add(PanCouleur);

        CentreDroit.add(PCouleur);

        PPhoto.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setText("Appuyer sur l'image:");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        PPhoto.add(jButton2);

        Photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoActionPerformed(evt);
            }
        });
        PPhoto.add(Photo);

        CentreDroit.add(PPhoto);

        Droite.add(CentreDroit, java.awt.BorderLayout.CENTER);

        Centre.add(Droite);

        getContentPane().add(Centre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCouleurActionPerformed
        JColorChooser diag = new JColorChooser();//instanciation d'une boite de dialogue de type JColorChooser
        Color coul = diag.showDialog(this,"Couleur",Color.red);//récupération de la couleur choisit dans la boite de dialogue dans coul(onaffecte des données en parametres de la boite comme la couleur par défaut ou le titre)
        if(coul!=null){//si une couleur à été choisit donc différentes de null
            nj.setCouleur(coul); //on affecte à nj la couleur cou sélectionné auparavant avce la méthode setCouleur()
            PanCouleur.setBackground(coul);//PanCouleur va se voir affecter en fond la couleur affecter à coul
        }
    }//GEN-LAST:event_BCouleurActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        this.nj.setPseudo(Pseudo.getText());//on affcete à l'attribut pseudo le texte rentré dans Pseudo
        if(this.nj.getPseudo().equals("")){//si aucun pseudo n'a été rentré
            JOptionPane option = new JOptionPane();//instanciation d'une JOptionPan (affichage d'information dans une boite de dialogue)
            option.showMessageDialog(this, "Aucun pseudo n'a été rentrer","Jeu Loto",JOptionPane.WARNING_MESSAGE);//on indique l'information au joueur
        }
        else{//sinon
            this.nj.setSolde(Double.parseDouble(Solde.getText()));//le solde du joueur est fixé en fonction du solde rentré dans Solde
            this.nj.setPhoto((ImageIcon)Photo.getIcon());//l'image est fixé en fonction de l'image affecter dans Photo
            this.ok = true;//attribut pour vérifier si la boite de dialogue est fermé passe à true
            this.setVisible(false);//on fait disparaitre la boite de dialogue
            this.dispose();//on l'a supprime
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        setVisible(false);//on fait disparaitre la boite de dialogue
        dispose();//on l'a supprime
    }//GEN-LAST:event_AnnulerActionPerformed

    private void PhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoActionPerformed
        int i = (int)(Math.random()*5);//choix aléatoire d'une valeur entre 0 et 4
        ImageIcon img = new ImageIcon();//instanciation de img de type ImageIcon
        LesImages image = new LesImages();//instanciation de image de type LesImages
        for(int x=0; x<image.getTailleLesImage(); x++){//boucle parcourant l'intégralité de la liste d'image
            if(i==x){//si l'entier est égal à la postion d'une image
                img = image.getImage(i);//img se voit récupérer l'image à la position i
                img = new ImageIcon(img.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));//affectation d'une nouvelle taille à l'image img
                Photo.setIcon(img);//on affecte l'image img dans Photo
            }
        }
    }//GEN-LAST:event_PhotoActionPerformed
    
    public boolean getOk(){//getter classique pour permettre de récupérer le boolean de validation de fermeture de ok
        return this.ok;
    }
    public Joueur getJoueur(){//getter classique pour permettre de récupérer le joueur nj
        return this.nj;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton BCouleur;
    private javax.swing.JPanel Centre;
    private javax.swing.JPanel CentreDroit;
    private javax.swing.JPanel CentreGauche;
    private javax.swing.JPanel Droite;
    private javax.swing.JPanel Gauche;
    private javax.swing.JPanel PCouleur;
    private javax.swing.JPanel PPhoto;
    private javax.swing.JPanel PValider;
    private javax.swing.JPanel PanCouleur;
    private javax.swing.JButton Photo;
    private javax.swing.JPanel PiedGauche;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JTextField Solde;
    private javax.swing.JLabel T1;
    private javax.swing.JLabel T2;
    private javax.swing.JLabel T3;
    private javax.swing.JLabel T4;
    private javax.swing.JPanel Titre;
    private javax.swing.JButton Valider;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
