/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeuloto;
import java.awt.*;
import javax.swing.*;
import java.util.ArrayList;
/**
 *
 * @author bast
 */
public class AjoutLotDlg extends javax.swing.JDialog {
    private Lots lot;//création d'un objet lot de type Lots
    private String descriptif;//descriptif du lot
    private String categorie;//categorie du lot
    private Image img;//image du lot
    private int niveau;//niveau du lot
    private ArrayList<String> bons = new ArrayList();
    private boolean ok=false;//boolean pour retourner le lot
    /**
     * Creates new form AjoutLotDlg
     */
    public AjoutLotDlg(java.awt.Frame parent, boolean modal) {//constructeur de AjoutLotDlg
        super(parent, modal);//appel de la méthode de la classe mère
        initComponents();//initialisation des composants
        lot = new Lots();//instanciation de lot de type Lots
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupeCategorie = new javax.swing.ButtonGroup();
        GroupeNiveau = new javax.swing.ButtonGroup();
        PTitre = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        PFoot = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        PCentre = new javax.swing.JPanel();
        PGauche = new javax.swing.JPanel();
        Descriptif = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Image = new javax.swing.JPanel();
        PDroit = new javax.swing.JPanel();
        Parametres = new javax.swing.JPanel();
        Des = new javax.swing.JTextField();
        Categorie = new javax.swing.JPanel();
        boncadeau = new javax.swing.JRadioButton();
        objet = new javax.swing.JRadioButton();
        Niveau = new javax.swing.JPanel();
        Niveau1 = new javax.swing.JRadioButton();
        Niveau2 = new javax.swing.JRadioButton();
        Niveau3 = new javax.swing.JRadioButton();
        Option = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PTitre.setLayout(new java.awt.BorderLayout());

        Titre.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titre.setText("Saisie d'un nouveau lot");
        PTitre.add(Titre, java.awt.BorderLayout.CENTER);

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PFoot.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        PFoot.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        PFoot.add(Valider);

        getContentPane().add(PFoot, java.awt.BorderLayout.PAGE_END);

        PCentre.setLayout(new java.awt.GridLayout(1, 2));

        PGauche.setLayout(new java.awt.GridLayout(2, 1));

        Descriptif.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descriptif");
        Descriptif.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Catégorie");
        Descriptif.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Niveau");
        Descriptif.add(jLabel3);

        PGauche.add(Descriptif);

        Image.setLayout(new java.awt.GridLayout(1, 1));
        PGauche.add(Image);

        PCentre.add(PGauche);

        PDroit.setLayout(new java.awt.GridLayout(2, 1));

        Parametres.setLayout(new java.awt.GridLayout(3, 1));
        Parametres.add(Des);

        Categorie.setLayout(new java.awt.GridLayout(1, 2));

        GroupeCategorie.add(boncadeau);
        boncadeau.setText("Bon Cadeau");
        boncadeau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boncadeauActionPerformed(evt);
            }
        });
        Categorie.add(boncadeau);

        GroupeCategorie.add(objet);
        objet.setText("Objet");
        objet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objetActionPerformed(evt);
            }
        });
        Categorie.add(objet);

        Parametres.add(Categorie);

        Niveau.setLayout(new java.awt.GridLayout(1, 3));

        GroupeNiveau.add(Niveau1);
        Niveau1.setText("1");
        Niveau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niveau1ActionPerformed(evt);
            }
        });
        Niveau.add(Niveau1);

        GroupeNiveau.add(Niveau2);
        Niveau2.setText("2");
        Niveau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niveau2ActionPerformed(evt);
            }
        });
        Niveau.add(Niveau2);

        GroupeNiveau.add(Niveau3);
        Niveau3.setText("3");
        Niveau3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niveau3ActionPerformed(evt);
            }
        });
        Niveau.add(Niveau3);

        Parametres.add(Niveau);

        PDroit.add(Parametres);

        Option.setLayout(new java.awt.GridLayout(2, 1));
        PDroit.add(Option);

        PCentre.add(PDroit);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Niveau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niveau1ActionPerformed
        if(boncadeau.isSelected()){//si le bouton sélectionnant les bons cadeaux est coché
            AjoutComboNiveau1();//ajout d'une JComboBox avec des valeurs de niveau 1 à l'intérieur et de la Arrylist bons
            DefaultComboBoxModel mod = new DefaultComboBoxModel(this.bons.toArray());//instanciation d'une DefaultComboBoxModel mod avec en parametre la ArrayList bon
            JComboBox box = (JComboBox)Option.getComponent(0);//récupération de la JComboBox box qui est dans le panneau Option
            box.setModel(mod);//on affecte le model par défaut à box
        }
    }//GEN-LAST:event_Niveau1ActionPerformed

    private void Niveau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niveau2ActionPerformed
        if(boncadeau.isSelected()){//si le bouton sélectionnant les bons cadeaux est coché
            AjoutComboNiveau2();//ajout d'une JComboBox avec des valeurs de niveau 2 à l'intérieur et de la Arrylist bons
            DefaultComboBoxModel mod = new DefaultComboBoxModel(this.bons.toArray());//instanciation d'une DefaultComboBoxModel mod avec en parametre la ArrayList bon
            JComboBox box = (JComboBox)Option.getComponent(0);//récupération de la JComboBox box qui est dans le panneau Option
            box.setModel(mod);//on affecte le model par défaut à box
        }
    }//GEN-LAST:event_Niveau2ActionPerformed

    private void Niveau3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niveau3ActionPerformed
        if(boncadeau.isSelected()){//si le bouton sélectionnant les bons cadeaux est coché
            AjoutComboNiveau3();//ajout d'une JComboBox avec des valeurs de niveau 3 à l'intérieur et de la Arrylist bons
            DefaultComboBoxModel mod = new DefaultComboBoxModel(this.bons.toArray());//instanciation d'une DefaultComboBoxModel mod avec en parametre la ArrayList bon
            JComboBox box = (JComboBox)Option.getComponent(0);//récupération de la JComboBox box qui est dans le panneau Option
            box.setModel(mod);//on affecte le model par défaut à box
        }
    }//GEN-LAST:event_Niveau3ActionPerformed

    private void boncadeauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boncadeauActionPerformed
        Image.removeAll();//on supprime ce qu'il y a dans le panneau Image
        Option.removeAll();//on supprime ce qu'il y a dans le panneau Option
        JComboBox box = new JComboBox();//instanciation d'une JComboBox nommé box
        Option.add(box);//ajout de box dans Option
        Option.repaint();//réaffichage de Option
        Image.repaint();//réaffichage de Image
    }//GEN-LAST:event_boncadeauActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        if(boncadeau.isSelected()){//si le bon cadeau est sélectionné
            this.categorie = "Bon Cadeau";//l'attribut catégorie se voit ajouter "Bon Cadeau"
            JComboBox box = (JComboBox)Option.getComponent(0);//Composant de type JComboBox box récupérer dans Option
            this.niveau = box.getSelectedIndex()+1;//on affcete un niveau (on ajoute 1 car l'index est initialement à 0)
            if(Niveau1.isSelected()){//si le niveau 1 est sélectionné
                this.descriptif = "Bon d'achat "+Des.getText()+" de "+(this.niveau*10)+"€";
                this.niveau=1;//ajout des informations dans descriptif et niveau
            }
            else if(Niveau2.isSelected()){//si le niveau 2 est sélectionné
                this.descriptif = "Bon d'achat "+Des.getText()+" de "+(30+this.niveau*10)+"€";
                this.niveau=2;//ajout des informations dans descriptif et niveau
            }
            else if(Niveau3.isSelected()){//si le niveau 3 est sélectionné
                this.descriptif = "Bon d'achat "+Des.getText()+" de "+(60+this.niveau*10)+"€";
                this.niveau=3;//ajout des informations dans descriptif et niveau
            }
            this.lot = new Lots(this.descriptif,this.categorie,this.niveau);//instanciation de Lots avec des parametres rentrés auparavant
            this.ok = true;//boolean pour savoir si la boite est bien fermé passe à true
            this.setVisible(false);//on fait disparaitre la boite
        }
        else if(objet.isSelected()){//si un object est sélectionné
            this.categorie = "Objet";//categorie se voit ajouter Object
            if(Niveau1.isSelected()){//si le niveau 1 est sélectionné
                this.descriptif = Des.getText();//on récupère le texte dans Des
                this.niveau=1;//ajout des informations dans niveau
            }
            else if(Niveau2.isSelected()){//si le niveau 2 est sélectionné
                this.descriptif = Des.getText();//on récupère le texte dans Des
                this.niveau=2;//ajout des informations dans niveau
            }
            else if(Niveau3.isSelected()){//si le niveau 3 est sélectionné
                this.descriptif = Des.getText();//on récupère le texte dans Des
                this.niveau=3;//ajout des informations dans niveau
            }
            this.lot = new Lots(this.descriptif,this.categorie,this.niveau);//instanciation de Lots avec des parametres rentrés auparavant
            this.ok = true;//boolean pour savoir si la boite est bien fermé passe à true
            this.setVisible(false);//on fait disparaitre la boite
        }
        else if(this.Descriptif.equals("")){
            JOptionPane option = new JOptionPane();//sinon ouverture d'un JOptionPan rappelant aux joueur qu'il a besoin d'un descriptif pour le lot
            option.showMessageDialog(this, "Impossible de valider le choix du lot si il n'y a pas de descriptif","Jeu Loto",JOptionPane.WARNING_MESSAGE);
        }
        else{
            JOptionPane option = new JOptionPane();//sinon ouverture d'un JOptionPan rappelant aux joueur qu'il a besoin d'un lot pour gagner
            option.showMessageDialog(this, "Impossible de valider le choix du lot si il n'y a pas de lots","Jeu Loto",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private void objetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objetActionPerformed
        Image.removeAll();//on supprime ce qu'il y a dans le panneau Image
        Option.removeAll();//on supprime ce qu'il y a dans le panneau Option
        PanneauImage panimage = new PanneauImage();//Instanciation d'un object de type PanneauImage
        Image.add(panimage);//on ajoute panimage dans Image
        JPanel pan = new JPanel();//Instanciation de JPanel pour combler un trou dans l'affichage
        Option.add(pan);//ajout de pan dans Option
        JButton choix = new JButton();//Instanciation d'un bouton choix
        choix.setText("Parcourir");//choix se voit ajouter un texte
        choix.addActionListener(new java.awt.event.ActionListener(){//ajout d'un écouteur sur le bouton bout
                public void actionPerformed(java.awt.event.ActionEvent evt){//ajout d'un event sur le bouton de type actionPerformed
                    boutonActionPerformed(evt); //appel de la méthode boutonActionPerformed lors d'une clique sur le bouton: Transfert de données
                }
            });
        Option.add(choix);//ajout de choix dans Option
        revalidate();//rafraichissement de la page
    }//GEN-LAST:event_objetActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        this.setVisible(false);//on fait disparaitre la boite de dialogue
        dispose();//on l'a supprime
    }//GEN-LAST:event_AnnulerActionPerformed

    public void AjoutComboNiveau1(){
        ArrayList<String>lots = new ArrayList();//Instanciation d'une ArrayList
        lots.add("10 euros");
        lots.add("20 euros");
        lots.add("30 euros");
        this.bons = lots;
    }
    
    public void AjoutComboNiveau2(){
        ArrayList<String>lots = new ArrayList();//Instanciation d'une ArrayList
        lots.add("40 euros");
        lots.add("50 euros");
        lots.add("60 euros");
        this.bons = lots;
    }
    
    public void AjoutComboNiveau3(){
        ArrayList<String>lots = new ArrayList();//Instanciation d'une ArrayList
        lots.add("70 euros");
        lots.add("80 euros");
        lots.add("90 euros");
        this.bons = lots;
    }
   
    private void boutonActionPerformed(java.awt.event.ActionEvent evt){
        JFileChooser jf = new JFileChooser();
        if(jf.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){//on ouvre et on recupere la valeur de retour
            String path = jf.getSelectedFile().getPath();//retourne un object de type file qui ici renvoie une méthode de la classe File
            Image img = Toolkit.getDefaultToolkit().getImage(path);//On crée une instance d'Image avec ce fichier
            PanneauImage PanImage = (PanneauImage)Image.getComponent(0);
            this.img  = img;
            PanImage.setImage(img);
        }
    }
    
    public Lots getLot(){//getter classique pour récupérer l'attribut lot
        return this.lot;
    }
    
    public boolean getOk(){//getter pour récuéprer le boolean ok
        return this.ok;
    }
    
    public Image getImage(){//getter pour récupérer une Image img
        return this.img;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JPanel Categorie;
    private javax.swing.JTextField Des;
    private javax.swing.JPanel Descriptif;
    private javax.swing.ButtonGroup GroupeCategorie;
    private javax.swing.ButtonGroup GroupeNiveau;
    private javax.swing.JPanel Image;
    private javax.swing.JPanel Niveau;
    private javax.swing.JRadioButton Niveau1;
    private javax.swing.JRadioButton Niveau2;
    private javax.swing.JRadioButton Niveau3;
    private javax.swing.JPanel Option;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PFoot;
    private javax.swing.JPanel PGauche;
    private javax.swing.JPanel PTitre;
    private javax.swing.JPanel Parametres;
    private javax.swing.JLabel Titre;
    private javax.swing.JButton Valider;
    private javax.swing.JRadioButton boncadeau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton objet;
    // End of variables declaration//GEN-END:variables
}
