/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeuloto;

/**
 *
 * @author bast
 */
public class ErrorPlayerDlg extends javax.swing.JDialog {//déclaration de la classe ErrorPlayerDlg 

    /**
     * Creates new form Error
     */
    public ErrorPlayerDlg(java.awt.Frame parent, boolean modal) {//constrcuteur classique d'une boite de dialogue
        super(parent, modal);//appel de la méthode du parent
        initComponents();//initialisation des boutons
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PFoot = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        PCentre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PFoot.add(jButton1);

        getContentPane().add(PFoot, java.awt.BorderLayout.PAGE_END);

        PCentre.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("       Impossible de rajouter un nouveau joueur, jeu limité à 4 participants       ");
        jLabel1.setToolTipText("");
        PCentre.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);//fait disparaitre la boite de dialogue
        dispose();//ferme la boite de dialogue
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PFoot;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
