/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jeuloto;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author bast
 */
public class VisuJoueurDlg extends javax.swing.JDialog {
    private Joueur lejoueur;//attribut de type joueur
    /** Creates new form VisuJoueurDlg */
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal,Joueur j) {//constructeur de VisuJoueurDlg
        super(parent, modal);//systeme de hiérarchie par rapport à la bibliothèque javax.swing.JDialog
        initComponents();//initialisation des composants
        this.lejoueur = j;//attribut lejoueur prends le joueur passé en parametre
        initInfos();//initialisation des informations
    }
    
    private void initInfos(){
        Pseudo.setText(lejoueur.getPseudo());//Pseudo se voit ajouter comme texte le pseudo que l'on récupère de l'attribut lejoueur
        Couleur.setBackground(lejoueur.getCouleur());//Couleur se voit ajouter en Background la couleur récupérer de l'attribut lejoueur
        Solde.setText(""+lejoueur.getSolde());//Solde se voit ajouter le solde récupérer depuis lejoueur
        Photo.setIcon(lejoueur.getPhoto());//Photo se voit ajouter un Icon que l'on récupère depuis l'attribut le joueur
        Edition.setText("Le joueur s'appelle "+lejoueur.getPseudo()+"\n\n");//Edition se voit ajouter plusieurs informations de lejoueur sous forme de phrase
        Edition.append("Il aime la couleur : "+lejoueur.getCouleur().toString()+"\n\n");
        Edition.append("Il dispose de la somme de "+lejoueur.getSolde()+"\n\n");
        Edition.append(lejoueur.toString());
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre = new javax.swing.JPanel();
        Titre_1 = new javax.swing.JLabel();
        Centre = new javax.swing.JPanel();
        PGauche = new javax.swing.JPanel();
        PiedGauche = new javax.swing.JPanel();
        CentreGauche = new javax.swing.JPanel();
        LabelPseudo = new javax.swing.JLabel();
        Pseudo = new javax.swing.JLabel();
        LabelCouleur = new javax.swing.JLabel();
        Couleur = new javax.swing.JPanel();
        LabelSolde = new javax.swing.JLabel();
        Solde = new javax.swing.JLabel();
        PDroit = new javax.swing.JPanel();
        PiedDroit = new javax.swing.JPanel();
        Fermer = new javax.swing.JButton();
        CentreDroit = new javax.swing.JPanel();
        Box = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        Photo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titre_1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Titre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titre_1.setText("Informations relatives à un joueur");
        Titre.add(Titre_1);

        getContentPane().add(Titre, java.awt.BorderLayout.PAGE_START);

        Centre.setLayout(new java.awt.GridLayout(1, 2));

        PGauche.setLayout(new java.awt.BorderLayout());

        PiedGauche.setLayout(new java.awt.GridLayout(1, 1));
        PGauche.add(PiedGauche, java.awt.BorderLayout.PAGE_END);

        CentreGauche.setLayout(new java.awt.GridLayout(3, 2));

        LabelPseudo.setFont(new java.awt.Font("Milestone Free Version", 3, 18)); // NOI18N
        LabelPseudo.setText("Pseudo");
        CentreGauche.add(LabelPseudo);
        CentreGauche.add(Pseudo);

        LabelCouleur.setFont(new java.awt.Font("Milestone Free Version", 3, 18)); // NOI18N
        LabelCouleur.setText("Couleur");
        CentreGauche.add(LabelCouleur);

        javax.swing.GroupLayout CouleurLayout = new javax.swing.GroupLayout(Couleur);
        Couleur.setLayout(CouleurLayout);
        CouleurLayout.setHorizontalGroup(
            CouleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        CouleurLayout.setVerticalGroup(
            CouleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        CentreGauche.add(Couleur);

        LabelSolde.setFont(new java.awt.Font("Milestone Free Version", 3, 18)); // NOI18N
        LabelSolde.setText("Solde");
        CentreGauche.add(LabelSolde);
        CentreGauche.add(Solde);

        PGauche.add(CentreGauche, java.awt.BorderLayout.CENTER);

        Centre.add(PGauche);

        PDroit.setLayout(new java.awt.BorderLayout());

        PiedDroit.setLayout(new java.awt.GridLayout(1, 1));

        Fermer.setText("Fermer");
        Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerActionPerformed(evt);
            }
        });
        PiedDroit.add(Fermer);

        PDroit.add(PiedDroit, java.awt.BorderLayout.PAGE_END);

        CentreDroit.setLayout(new java.awt.GridLayout(1, 2));

        Edition.setEditable(false);
        Edition.setColumns(20);
        Edition.setRows(5);
        Box.setViewportView(Edition);

        CentreDroit.add(Box);
        CentreDroit.add(Photo);

        PDroit.add(CentreDroit, java.awt.BorderLayout.CENTER);

        Centre.add(PDroit);

        getContentPane().add(Centre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed
        setVisible(false);//lors de l'appuie sur le bouton Fermer, la boite de dialogue va pouvoir se fermer
        dispose();
    }//GEN-LAST:event_FermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Joueur x= new Joueur();
                VisuJoueurDlg dialog = new VisuJoueurDlg(new javax.swing.JFrame(), true,x);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Box;
    private javax.swing.JPanel Centre;
    private javax.swing.JPanel CentreDroit;
    private javax.swing.JPanel CentreGauche;
    private javax.swing.JPanel Couleur;
    private javax.swing.JTextArea Edition;
    private javax.swing.JButton Fermer;
    private javax.swing.JLabel LabelCouleur;
    private javax.swing.JLabel LabelPseudo;
    private javax.swing.JLabel LabelSolde;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PGauche;
    private javax.swing.JButton Photo;
    private javax.swing.JPanel PiedDroit;
    private javax.swing.JPanel PiedGauche;
    private javax.swing.JLabel Pseudo;
    private javax.swing.JLabel Solde;
    private javax.swing.JPanel Titre;
    private javax.swing.JLabel Titre_1;
    // End of variables declaration//GEN-END:variables

}
