/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeuloto;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author bast
 */
public class VisuLotDlg extends javax.swing.JDialog {

    /**
     * Creates new form VisuLotDlg
     */
    public VisuLotDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AjoutLot();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        North = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        Center = new javax.swing.JPanel();
        South = new javax.swing.JPanel();
        Fermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        North.setLayout(new java.awt.BorderLayout());

        Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titre.setText("Visualisation des lots");
        North.add(Titre, java.awt.BorderLayout.CENTER);

        getContentPane().add(North, java.awt.BorderLayout.PAGE_START);

        Center.setLayout(new java.awt.GridLayout(4, 2));
        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        South.setLayout(new java.awt.GridLayout(1, 1));

        Fermer.setText("Fermer");
        Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerActionPerformed(evt);
            }
        });
        South.add(Fermer);

        getContentPane().add(South, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed
        this.setVisible(false);//on fait disparaitre la boite de dialogue
        dispose();//on l'a supprime
    }//GEN-LAST:event_FermerActionPerformed
    
    public void AjoutLot(){//ajout des images dans le panneau 'Center' grâce à des PanneauImage
        Image img1 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jeuloto/Image_Lot/Bateau.png/"));//récupération de l'image
        PanneauImage pan1 = new PanneauImage(img1);//ajout d'une instance de PanneauImage avec en parametre l'image récupérer auparavant
        Center.add(pan1);//ajout du panneau dans 'Center'

        Image img2 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jeuloto/Image_Lot/Easter_Egg.png/"));
        PanneauImage pan2 = new PanneauImage(img2);
        Center.add(pan2);
        
        Image img3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jeuloto/Image_Lot/Fleurs.png/"));
        PanneauImage pan3 = new PanneauImage(img3);
        Center.add(pan3);
        
        Image img4 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jeuloto/Image_Lot/Pack_Media.png/"));
        PanneauImage pan4 = new PanneauImage(img4);
        Center.add(pan4);
        
        Image img5 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jeuloto/Image_Lot/Twingo.png/"));
        PanneauImage pan5 = new PanneauImage(img5);
        Center.add(pan5);
        
        Image img6 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jeuloto/Image_Lot/raclette.png/"));
        PanneauImage pan6 = new PanneauImage(img6);
        Center.add(pan6);
        
        Image img7 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jeuloto/Image_Lot/robot_culinaire.png/"));
        PanneauImage pan7 = new PanneauImage(img7);
        Center.add(pan7);
        
        Image img8 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jeuloto/Image_Lot/switch.png/"));
        PanneauImage pan8 = new PanneauImage(img8);
        Center.add(pan8);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuLotDlg dialog = new VisuLotDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JButton Fermer;
    private javax.swing.JPanel North;
    private javax.swing.JPanel South;
    private javax.swing.JLabel Titre;
    // End of variables declaration//GEN-END:variables
}
